name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Instalar Bun
        uses: oven-sh/setup-bun@v2

      - name: Instalar dependencias
        run: bun install

      - name: Compilar proyecto
        run: bun run build
